esphome:
  name: abstellraum

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "0pq9tpmibtrDs8HuhL6BNGqqPnQIC6VNGv5lO3459N0="

ota:
  password: "f577215474a3d413b8a32ce21ae1bbd8"

time:
  - platform: homeassistant
    timezone: Europe/Vienna
    id: time_homeassistant

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Abstellraum Fallback Hotspot"
    password: "jJh2EPNFzg52"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: bmp085
    temperature:
      name: "Abstellraum Temperature"
    pressure:
      name: "Abstellraum Pressure"
    update_interval: 60s
  - platform: uptime
    name: "Abstellraum Uptime Sensor"
  - platform: wifi_signal
    name: "Abstellraum WiFi Signal Sensor"
    update_interval: 60s

i2c:
  sda: GPIO4
  scl: GPIO5